services:
    database:
        image: 'postgres:latest'
        volumes:
            - $HOME/docker/volumes/postgres:/var/lib/postgresql
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=docker
    server:
        build: ./server
        ports:
            - "8080:8080"
    client:
        build: ./client/docker-workshop-client
        ports:
            - "5173:5173"